### ISSUE TITLE
Total 0 solutions in 8429.2 ms (0.0 Sol/s)

### ISSUE THREAD

**Issue by danwxyz** [mbevand/silentarmy#1]
Hello. I am running silentarmy on Ubuntu 14.04 with a Radeon 7970 using proprietary drivers.

When running `$ make test` it seems to run fine without any errors. 

However, when running `$ silentarmy --nonces 100`, I end up with `Total 0 solutions in 8429.2 ms (0.0 Sol/s)`.

**Comment by buzzdave** [comment]
confirmed, zero sols on Tahiti class GPUs

**Comment by blenessy** [comment]
Also confirmed on 280x (also Tahiti).

**Comment by mbevand** [comment]
Ok I'm looking into this. I have not tested any GPU other than the RX 480 and R9 Nano.

**Comment by mbevand** [comment]
It looks like the determining factor is the GCN generation. Tahiti is GCN 1st gen. Silentarmy works on GCN 2nd, 3rd, and 4th gen cards, but not GCN 1st gen cards.

**Comment by mbevand** [comment]
I investigated this bug and found that unaligned memory accesses was the root cause of silentarmy reporting "0 solutions" on GCN 1st gen hardware.

I fixed it in https://github.com/mbevand/silentarmy/commit/5f68344448385e2aadd1c1f9e6c06d0a2267e7ff

Now silentarmy should work on all GPUs, regardless of GCN generation.
