### ISSUE TITLE
Implement stratum method client.reconnect

### ISSUE THREAD

**Issue by poiuty** [mbevand/silentarmy#16]
```
Stratum: invalid msg from server: Unimplemented method: client.reconnect: {'id': None, 'params': [], 'method': 'client.reconnect'}

Stratum: connection was closed (invalid user/pwd?)
Total 64.5 sol/s [dev0 32.4, dev1 31.4] 1243 shares
Connecting to equihash.eu.nicehash.com:3357 (attempt 6)
Stratum: SILENTARMY is not compatible with servers fixing the first 17 bytes of the nonce
```

**Comment by mbevand** [comment]
Yes I don't implement client.reconnect... but the error leads to a reconnection - so the end result is what we want but in a completely unintentional way :) I will look into properly supporting client.reconnect, eventually

**Comment by lexele** [comment]
I run on nicehash for like two hours this morning with sometimes this errors, until at some point the miner crashed. Afterwards I couldn't connect again to nicehash .

**Comment by n1koo** [comment]
Just had this happened to myself too. Not really related to the `client.reconnect` except that being the thing triggering it for @poiuty

**Comment by mbevand** [comment]
This error ("not compatible with servers fixing the first 17 bytes of the nonce") is because equihash.eu.nicehash.com resolves to 2 IP addresses: 5.153.50.217 and 37.58.117.214. And nicehash seems to be running different stratum configuration: one of them returns a nonce of 5 bytes (supported) and the other of 17 bytes (unsupported). During startup silentarmy has 50% chance of hitting the wrong server, so it gets this fatal error and aborts. Just try launching silentarmy again and it will eventually pick the right server :)

**Comment by mbevand** [comment]
I am going to close #16 since implementing client.reconnect is tracked in #17.

**Comment by kenshirothefist** [comment]
FYI (also posted on bitcointalk):

Please revise the official stratum documentation at https://slushpool.com/help/#!/manual/stratum-protocol. There are no such limitations, a nonce can be even larger. The fact that you're receiving different nonce sizes is not related to a particular NiceHash stratum endpoint. It is simply a fact that NiceHash is forwarding work from different hashing power orders, which are working on different target pools. Anyway, 17 bytes nonce is the largest (max) that you'll receive from NiceHash stratum and even at this size you still have 3 bytes for iteration. So there is no reason why not to accept this kind of work. Please fix this as soon as possible, since our users would really love to use your miner and are now not able to do so due to these limitations of your miner.

Thank you and keep up the good work!

**Comment by birdie-github** [comment]
So how am I supposed to use equihash.eu.nicehash.com:3557 with silentarmy?

All I get is "Stratum: connection was closed (invalid user/pwd?)"

Running master on CentOS 7.0/Python 3.4.

**Comment by kenshirothefist** [comment]
@birdie-github you're using wrong port - it's **3357** ... try again, please (add "#xnsub" after port to enable extranonce.subscription):

silentarmy -c stratum+tcp://equihash.eu.nicehash.com:3357#xnsub -u [YOUR-BTC-ADDRESS].[WORKER-NAME] -p x

**Comment by birdie-github** [comment]
@kenshirothefist 

Thank you! It helped.
