### ISSUE TITLE
Zero sols after few minutes of mine

### ISSUE THREAD

**Issue by asluchevskiy** [mbevand/silentarmy#18]
Hi, using ubuntu 14.04 (4.8.0-rc6) + amd gpu pro 16.30 on 6-card-rig (stable on ethereum + claymore). I have 0.0 (zero) sols after few minutes of mining. Hardware is Asrock H97 anniversary + RX470 refs.

[code]Total 197.1 sol/s [dev0 39.4, dev1 38.8, dev2 0.0, dev3 37.5, dev4 37.8, dev5 44.1] 35 shares
Total 197.3 sol/s [dev0 38.0, dev1 40.5, dev2 0.0, dev3 37.0, dev4 32.7, dev5 44.0] 35 shares
Total 194.5 sol/s [dev0 37.4, dev1 39.0, dev2 0.0, dev3 38.4, dev4 27.4, dev5 45.5] 35 shares
Total 192.3 sol/s [dev0 38.3, dev1 39.0, dev2 0.0, dev3 39.3, dev4 24.9, dev5 45.4] 35 shares
Total 190.8 sol/s [dev0 37.0, dev1 40.0, dev2 0.0, dev3 38.3, dev4 21.0, dev5 45.6] 35 shares
Total 191.1 sol/s [dev0 38.9, dev1 39.2, dev2 0.0, dev3 37.6, dev4 16.8, dev5 46.0] 35 shares
Total 189.3 sol/s [dev0 37.6, dev1 38.2, dev2 0.0, dev3 39.5, dev4 13.0, dev5 43.1] 35 shares
Total 187.1 sol/s [dev0 37.2, dev1 36.8, dev2 0.0, dev3 40.4, dev4 8.9, dev5 43.8] 35 shares
Total 187.2 sol/s [dev0 36.9, dev1 40.1, dev2 0.0, dev3 38.9, dev4 6.7, dev5 42.1] 35 shares
Total 186.2 sol/s [dev0 37.4, dev1 39.7, dev2 0.0, dev3 39.1, dev4 2.5, dev5 43.5] 35 shares
Total 184.4 sol/s [dev0 37.6, dev1 38.2, dev2 0.0, dev3 37.7, dev4 0.0, dev5 42.2] 35 shares
Total 183.4 sol/s [dev0 36.3, dev1 34.3, dev2 0.0, dev3 41.4, dev4 0.0, dev5 41.2] 35 shares
[/code]

If stop and restart miner threads could not been initialized, so I need to reboot. I am using zec.nanopool.org

Here is dmesg output: http://pastebin.com/fg5ZEiai

**Comment by mbevand** [comment]
Seems like bad hardware. Try removing device 4 from the "--use" option and run for a few hours. If it works fine, then your device 4 has a hardware issue. Check overclocking, powersupply, overheating, etc.

It is normal that a device may work fine mining one type of cryptocurrency, but not another type, because proof-of-work workloads are different and stress differents part of the hardware.

Closing this issue since it's almost certainly a non-software bug.
