### ISSUE TITLE
Getting bad interpreter error

### ISSUE THREAD

**Issue by wheatdogg** [mbevand/silentarmy#45]
Running Ubuntu 12.04LTS with Python 3.3, I get this error:

```
john@john-ubuntu:~/Desktop/silentarmy-4$ ./silentarmy --list
bash: ./silentarmy: /usr/bin/python3: bad interpreter: No such file or directory
```
clinfo returns my GPU info and sa-solver and make test both work fine. Any advice?

**Comment by mbevand** [comment]
It's because you don't have the binary "python3" installed. You need
specifically Python 3.3 or above. You may want to try these instructions:

http://askubuntu.com/questions/244544/how-do-i-install-python-3-3

However Ubuntu 12.04 is really old. You might encounter other issues trying
to run silentarmy.

-Marc

On Tue, Nov 8, 2016, 07:41 wheatdogg <notifications@github.com> wrote:

Running Ubuntu 12.04LTS with Python 3.3, I get this error:

john@john-ubuntu:~/Desktop/silentarmy-4$ ./silentarmy --list
bash: ./silentarmy: /usr/bin/python3: bad interpreter: No such file or directory

clinfo returns my GPU info and sa-solver and make test both work fine. Any
advice?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mbevand/silentarmy/issues/45>, or mute the thread

**Comment by wheatdogg** [comment]
I already installed Python 3.3. I found that all I needed to do was change `#! /usr/bin/python3` to `#! /usr/bin/python3.3` in the silentarmy code. Now it is running around 20 sol/s on my R9 370 with 2GB with the nicehash stratum pool.
